repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: pretty-format-json
        args: [--autofix,--no-sort-keys]
        types: [text]
        files: LPC/data/.*\.json$