// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ThirdParty/Public_0_PixiJsFilters","status":true,"description":"[RPG Maker MZ] [Tier 0] [Version 3.1.0] [Pixi JS Filters]","parameters":{}},
{"name":"ThirdParty/PluginCommonBase","status":true,"description":"Plugin Analysis Common Base","parameters":{}},
{"name":"ThirdParty/DevToolsManage","status":true,"description":"Development Support Plugin","parameters":{"StartupDevTool":"true","ShortcutList":"","ShowFPS":"OFF","CutTitle":"false","RapidStart":"false","RapidSpeed":"2","SlowSpeed":"2","InvalidMessageSkip":"false","MenuBarVisible":"true","ClickMenu":"1","OutputStartupInfo":"true","StartupOnTop":"false","UseReloadData":"true"}},
{"name":"LPC/LPC_Characters","status":true,"description":"use characters from Unlversal LPC Spritesheet Generator","parameters":{}},
{"name":"ThirdParty/VisuMZ_5_TiledMZ","status":true,"description":"[RPG Maker MZ] [Tier 5] [Version 0.16] [TiledMZ]","parameters":{"BreakHead":"----------------------------------","TiledMZ":"Plugin Parameters","ATTENTION":"READ THE HELP FILE","BreakSettings":"----------------------------------","BushDepth":"12","PriorityTileLimit":"256","ShadowVisibilitySwitch":"1","BreakEnd1":"----------------------------------","End Of":"Plugin Parameters","BreakEnd2":"----------------------------------"}}
];
